# Generated by Django 4.2.6 on 2024-03-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jay_profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
